<a href="https://colab.research.google.com/github/leehyobin3538/aipython/blob/main/240503.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=list(map(int,input().split()))

if sum(a)>100:
  if a[0]>40 and a[1]>40:
    print('PASS')
  elif a[0]<40:
    print('ENG FAIL')
  else:
    print('MATH FAIL')
else:
  print('FAIL')


60 60
PASS


In [ ]:
num=input()
numlist=list(num)
intnum=map(int,numlist)
print(sum(intnum))


1234
10


In [ ]:
n=int(input())
a=[input() for _ in range(n)]
b=[i for i in a if i.split('.')[-1]=='jpg' or i.split('.')[-1]=='png']
print(b)

2
dtdsa.png
adaf.dafd
['dtdsa.png']


In [ ]:
#1부터 10까지(미포함)의 2걸음 크기의 정수값 배열을 생성해보자


import numpy as np
arr=np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [ ]:
#모양이 (3,4)인 모든 값이 1인 배열을 생성해보자


ones_1d=np.ones((3,4))
print(ones_1d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
#0과 1사이를 10등분하고자 할 때 등분값 배열을 생성해보자


arr_1d=np.linspace(0,1,10)
print(arr_1d)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
A = np.array(
[[ 1, 2, 3, 4, 5],
 [ 6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20],
 [21, 22, 23, 24, 25]])

print(A.shape)
print(A[3,3])
print(A[:2,:2])
print(A[-1:,-2:])



(5, 5)
19
[[1 2]
 [6 7]]
[[24 25]]


In [ ]:
A = np.array([[[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9,10,11,12]],

[[13,14,15,16],
 [17,18,19,20],
 [21,22,23,24]],

 [[25,26,27,28],
 [29,30,31,32],
 [33,34,35,36]]])

print(A.shape)
print(A.size)
reA=A.reshape(3,4,3)
print(reA)


(3, 3, 4)
36
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
